# Generated by Django 5.2.15 on 2026-06-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lead_player',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='CustomPlayers',
        ),
    ]
