# Generated by Django 5.2.15 on 2026-06-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_team_lead_player_team_team_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='lead_player',
            new_name='team_leader',
        ),
    ]
