# Generated by Django 5.2.15 on 2026-06-25 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_lead_player_team_team_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('quiz_round', models.IntegerField(db_default=1)),
                ('question', models.IntegerField(db_default=1)),
                ('stage', models.IntegerField(choices=[(1, 'Lobby'), (2, 'Game'), (3, 'Round End'), (4, 'Game End')], db_default=1)),
            ],
        ),
    ]
