# Generated by Django 5.2.15 on 2026-07-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_gamestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Lobby'), (2, 'Quiz'), (3, 'Round End'), (4, 'Game End')], db_default=1),
        ),
    ]
