# Generated by Django 5.2.15 on 2026-07-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_gamestate_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='stage',
            new_name='room',
        ),
    ]
