# Generated by Django 5.2.15 on 2026-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_orderedquestion_round_orderedquestion_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
