# Generated by Django 5.2.15 on 2026-07-17 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_round_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.round')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('rounds', models.ManyToManyField(related_name='+', through='quiz.OrderedRound', to='quiz.round')),
            ],
        ),
        migrations.AddField(
            model_name='orderedround',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AlterUniqueTogether(
            name='orderedround',
            unique_together={('quiz', 'round')},
        ),
    ]
