# Generated by Django 5.2.15 on 2026-07-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_orderedround_quiz_orderedround_quiz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='quiz_round',
            new_name='round',
        ),
    ]
