# Generated by Django 5.2.15 on 2026-07-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_rename_quiz_round_gamestate_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multichoicequestion',
            name='round',
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'correct'), (3, 'incorrect')], db_default=1)),
                ('points', models.IntegerField(db_default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.gamestate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.team')),
            ],
        ),
    ]
