# Generated by Django 5.2.15 on 2026-07-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_multichoicequestion_round_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='question',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='room',
            field=models.IntegerField(choices=[(1, 'Lobby'), (2, 'Quiz'), (3, 'Round End'), (4, 'Game End')], default=1),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='submission',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'correct'), (3, 'incorrect')], default=1),
        ),
    ]
