# Generated by Django 5.2.15 on 2026-07-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_choice_is_correct_alter_gamestate_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedQuestion',
            new_name='RoundQuestion',
        ),
    ]
