# Generated by Django 5.2.15 on 2026-07-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_rename_orderedquestion_roundquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedRound',
            new_name='QuizRound',
        ),
    ]
