# Generated by Django 5.2.15 on 2026-07-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_submission_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='question',
            new_name='question_num',
        ),
        migrations.RenameField(
            model_name='gamestate',
            old_name='round',
            new_name='round_num',
        ),
    ]
