# Generated by Django 5.2.15 on 2026-07-19 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_rename_question_gamestate_question_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='quiz',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
