# Generated by Django 5.2.15 on 2026-07-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_gamestate_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='question_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='round_num',
            field=models.IntegerField(default=0),
        ),
    ]
