# Generated by Django 5.2.15 on 2026-07-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='code',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
