# Generated by Django 5.2.15 on 2026-07-20 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_gamestate_code_delete_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.gamestate'),
            preserve_default=False,
        ),
    ]
