# Generated by Django 5.2.15 on 2026-08-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_team_profile_pic_alter_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
