# Generated by Django 5.2.15 on 2026-08-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_alter_team_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
