# Generated by Django 5.2.15 on 2026-09-30 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_quiz_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextboxQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
            ],
            bases=('quiz.question',),
        ),
    ]
