# Generated by Django 5.2.15 on 2026-09-30 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_textboxquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Mcq'), (2, 'Textbox')], default=1),
        ),
        migrations.CreateModel(
            name='TextSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.submission')),
            ],
        ),
    ]
